//ここで順番とカラム表示とカラム名を全部制御する
export const ColumnMapping = [
  { key: 'farm_name', label: '商社' },
  { key: 'progress_name', label: '進捗' },
  { key: 'fullOrderCode', label: '受注番号' },
  { key: 'request_name', label: '依頼内容' },
  { key: 'customer_name', label: '顧客名' },
  { key: 'customer_location', label: '拠点' },
  { key: 'customer_department_name', label: '部署名' },
  { key: 'customer_group', label: 'グループ' },
  { key: 'customer_person', label: '担当者' },
  { key: 'item_code', label: '品番' },
  { key: 'item_name', label: '品名' },
  { key: 'lot', label: 'ロット_シリアル' },
  { key: 'soft', label: 'ソフトVer' },
  { key: 'quantity', label: '台数' },
  { key: 'estimate_date', label: '見積日' },
  { key: 'order_date', label: '受注日' },
  { key: 'desired_delivery_date', label: '希望納期' },
  { key: 'shipment_date', label: '出荷日' },
  { key: 'send_document_date', label: '書類送付日' },
  { key: 'receive_document_date', label: '資料受領日' },
  { key: 'item_receive_date', label: '現品受領日' },
  { key: 'item_return_date', label: '現品返却日' },
  { key: 'comment', label: '備考' },
  { key: 'customer_management_code', label: '注文番号' },
  { key: 'accept_date', label: '検収日' },
  //ここからは津田製作所様内だけの情報
  { key: 'priority_level', label: '優先度' },
  { key: 'estimate_code', label: '見積No' },
  { key: 'order_form_code', label: '注文書No' },
  { key: 'amount', label: '金額' },
  { key: 'created_at', label: '作成日' },
];
