export type OrderListDataType = {
  accept_date: string | null,
  amount: string | null,
  comment: string | null,
  created_at: string,
  customer: number | null,
  customer_department: number | null,
  customer_group: string | null,
  customer_location: string | null,
  customer_management_code: string | null,
  customer_person: string | null,
  desired_delivery_date: string | null,
  estimate_code: string | null,
  estimate_date: string | null,
  id: number,
  item_code: string | null,
  item_name: string | null,
  item_receive_date: string | null,
  item_return_date: string | null,
  lot: string | null,
  order_code: string,
  order_date: string | null,
  order_form_code: string | null,
  progress: number | null,
  quantity: number | null,
  receive_document_date: string | null,
  request: number | null,
  send_document_date: string | null,
  shipment_date: string | null,
  soft: string | null
};
